backend:
  name: git-gateway
  branch: main

media_folder: "assets/images/uploads"        # Où stocker les images uploadées
public_folder: "/assets/images/uploads"      # Chemin depuis le site

collections:
  - name: "galerie"
    label: "Galerie IA"
    folder: "_galerie"                       # Dossier des fichiers Markdown
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titre",       name: "title",       widget: "string" }
      - { label: "Image",       name: "image",       widget: "image"  }
      - { label: "Description", name: "body",        widget: "text"   }
