backend:
  name: git-gateway
  branch: main

media_folder: "assets/images/upload"
public_folder: "/assets/images/upload"

collections:
  - name: "galerie"
    label: "Galerie IA"
    folder: "assets/images/upload"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
